# Generated by Django 5.2.9 on 2025-12-17 10:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bathroomvisit",
            options={"ordering": ["-deployed_at"]},
        ),
        migrations.AddField(
            model_name="bathroomvisit",
            name="deployed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
